const state = { token: localStorage.getItem('asthi_admin_token') || '' };
const $ = id => document.getElementById(id);
function api(path, options = {}) {
  return fetch(path, { ...options, headers: { 'Content-Type': 'application/json', ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}), ...(options.headers || {}) } }).then(async r => { const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.error || 'Error de servidor.'); return data; });
}
function showPanel(){ $('login').hidden=true; $('panel').hidden=false; refresh(); }
function showLogin(){ $('login').hidden=false; $('panel').hidden=true; }
async function login(){ try { const data=await api('/api/admin/login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})}); state.token=data.token; localStorage.setItem('asthi_admin_token',state.token); $('loginMsg').textContent=''; showPanel(); } catch(e){ $('loginMsg').textContent=e.message; } }
async function refresh(){ try { const [dash,users,keys]=await Promise.all([api('/api/admin/dashboard'),api('/api/admin/users'),api('/api/admin/keys')]); $('totalUsers').textContent=dash.users.total; $('activeUsers').textContent=dash.users.active; $('inactiveUsers').textContent=dash.users.inactive; $('installations').textContent=dash.installations.total; renderKeys(keys.keys); renderUsers(users.users); renderSlots(keys.keys); } catch(e){ if(/sesión|autorizado/i.test(e.message)){ state.token='';localStorage.removeItem('asthi_admin_token');showLogin(); } else alert(e.message); } }
function renderKeys(keys){ $('keys').innerHTML=keys.map(k=>`<div class="key"><strong>${k.label}</strong><small>${k.configured?'Configurada':'No configurada'} · ${k.active?'Activa':'Inactiva'}</small><input id="key-${k.slot}" type="password" placeholder="Nueva clave"><button data-save="${k.slot}">Guardar</button><button class="secondary" data-toggle="${k.slot}" data-active="${k.active}">${k.active?'Desactivar':'Activar'}</button></div>`).join(''); document.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{const slot=b.dataset.save;const value=$(`key-${slot}`).value;if(!value)return alert('Escribe una nueva clave.');await api(`/api/admin/keys/${slot}`,{method:'POST',body:JSON.stringify({key:value})});$(`key-${slot}`).value='';await refresh();});document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{const slot=b.dataset.toggle;await api(`/api/admin/keys/${slot}`,{method:'PATCH',body:JSON.stringify({active:b.dataset.active!=='true'})});await refresh();}); }
function renderSlots(keys){$('keySlot').innerHTML=keys.filter(k=>k.active&&k.configured).map(k=>`<option value="${k.slot}">${k.label}</option>`).join('');}
function renderUsers(users){$('users').innerHTML=users.map(u=>`<tr><td>${escapeHtml(u.name)}</td><td>${u.key}</td><td class="state ${u.active?'on':'off'}">${u.active?'Activo':'Inactivo'}</td><td>${u.last_login_at?new Date(u.last_login_at).toLocaleString():'Nunca'}</td><td class="actions"><button data-user-toggle="${u.id}" data-active="${u.active}">${u.active?'Bloquear':'Activar'}</button><button class="danger" data-user-delete="${u.id}">Eliminar</button></td></tr>`).join('');document.querySelectorAll('[data-user-toggle]').forEach(b=>b.onclick=async()=>{await api(`/api/admin/users/${b.dataset.userToggle}`,{method:'PATCH',body:JSON.stringify({active:b.dataset.active!=='true'})});await refresh();});document.querySelectorAll('[data-user-delete]').forEach(b=>b.onclick=async()=>{if(confirm('¿Eliminar este usuario?')){await api(`/api/admin/users/${b.dataset.userDelete}`,{method:'DELETE'});await refresh();}});}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
async function createUser(){try{const data={firstName:$('firstName').value,firstSurname:$('firstSurname').value,keySlot:Number($('keySlot').value),active:$('userActive').checked};await api('/api/admin/users',{method:'POST',body:JSON.stringify(data)});$('firstName').value='';$('firstSurname').value='';$('userMsg').textContent='Usuario creado.';await refresh();}catch(e){$('userMsg').textContent=e.message;}}
$('loginBtn').onclick=login;$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('createUserBtn').onclick=createUser;$('logoutBtn').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}state.token='';localStorage.removeItem('asthi_admin_token');showLogin()};if(state.token)showPanel();
